### ISSUE TITLE
[Feature] - Add configurable border options

### ISSUE THREAD

**Issue by noullove** [caliguIa/zendiagram.nvim#1]
I prefer a UI with a visible border, but this plugin has its border setting set to “none” by default, and there is no option to change it. Please add an option to make this configurable. Thank you!

Additionally, there is an issue where Markdown rendering does not work properly when using the following settings.

``` nvim
vim.api.nvim_create_autocmd("LspAttach", {
  desc = "Floating diagnostics on CursorHold",
  callback = function()

    vim.diagnostic.config({
      virtual_text = false, 
    })

    vim.api.nvim_create_autocmd("CursorHold", {
      callback = function()
        require('zendiagram').open()
      end,
    })
  end,
})
```

<img width="789" alt="Image" src="https://github.com/user-attachments/assets/dfe5d908-4b17-4f9d-ac0a-5c6d1da1fa9c" />

For reference, I am using the following plugin for Markdown rendering.

``` nvim
{
  "MeanderingProgrammer/render-markdown.nvim",
   after = { "nvim-treesitter" },
   requires = {
       "nvim-tree/nvim-web-devicons", opt = true -- if you prefer nvim-web-devicons
   },
   opts = {
     enabled = true,
     file_types = { "markdown" },
   },
   ft = { "markdown" },
},
```

**Comment by caliguIa** [comment]
Hi,

Thanks for checking out the plugin. Ha, yes of course people would want to change the border settings.... my bad! I'll add in an option for that. 

Let me take a look at fixing the rendering issue as well. I may come back with some questions if that's alright.

**Comment by noullove** [comment]
@caliguIa Yes, of course! Feel free to ask if you have any questions. I hope this can help improve the functionality. Thank you!

**Comment by noullove** [comment]
@caliguIa 

<img width="742" alt="Image" src="https://github.com/user-attachments/assets/ff3e97ab-e393-49d1-b65e-b85184cae911" />

It looks like the second issue was resolved with an update to the render-markdown plugin. However, there is still an issue where the title is not rendered when it gains focus.

If it were possible to distinguish the window, I could have modified the focusing behavior using autocmd. However, since it’s not possible to differentiate the window, I’d like to request a fix. Thank you!

**Comment by caliguIa** [comment]
Hi, I'm going to take a look at these tomorrow for you. Good to hear the rendering issue was solved for you, I'll have a test with some different versions of render-markdown.nvim and add a recommended min version to the readme. 

Just to clarify, when you say the title is not rendered, do you mean render-markdown is displaying the characters as opposed to "rendered" title? The same is true if you move your cursor down to the codeblock I'm assuming. I will look at solving this. And lastly when you say "if it were possible to distinguish the window" are you referring to the window having a file type? If so I thought I'd given it a type of "ZendiagramFloat", but I may have broken that somehow, again will take a look.

Thanks again for the info and I'll let you know once I've solved!

**Comment by noullove** [comment]
> Hi, I'm going to take a look at these tomorrow for you. Good to hear the rendering issue was solved for you, I'll have a test with some different versions of render-markdown.nvim and add a recommended min version to the readme.
> 
> Just to clarify, when you say the title is not rendered, do you mean render-markdown is displaying the characters as opposed to "rendered" title? The same is true if you move your cursor down to the codeblock I'm assuming. I will look at solving this. And lastly when you say "if it were possible to distinguish the window" are you referring to the window having a file type? If so I thought I'd given it a type of "ZendiagramFloat", but I may have broken that somehow, again will take a look.
> 
> Thanks again for the info and I'll let you know once I've solved!

It seems that the issue occurs because the window gains focus. In the case of render-markdown, the area where the cursor is located is not rendered, which causes this problem. Additionally, moving the focus makes it inconvenient when modifying the code. If this part is fixed, everything should be fine.

**Comment by noullove** [comment]
> Hi, I'm going to take a look at these tomorrow for you. Good to hear the rendering issue was solved for you, I'll have a test with some different versions of render-markdown.nvim and add a recommended min version to the readme.
> 
> Just to clarify, when you say the title is not rendered, do you mean render-markdown is displaying the characters as opposed to "rendered" title? The same is true if you move your cursor down to the codeblock I'm assuming. I will look at solving this. And lastly when you say "if it were possible to distinguish the window" are you referring to the window having a file type? If so I thought I'd given it a type of "ZendiagramFloat", but I may have broken that somehow, again will take a look.
> 
> Thanks again for the info and I'll let you know once I've solved!

Sorry for the confusion. I tried running Neovim in a clean state, and the issue appears exactly as I initially reported, regardless of render-markdown. The text is displayed in an unrendered markdown format. When I mentioned that it was resolved, it seems something got mixed up, causing it to appear that way. In the end, the issue remains the same as I originally described.

**Comment by noullove** [comment]
@caliguIa 

[user.patch](https://github.com/user-attachments/files/18917245/user.patch)

I have attached a patch file where I added the border option and fixed the markdown rendering issue. Please review it.

**Comment by caliguIa** [comment]
Hi, I've merged two prs addressing your issues. Thanks again
